# -*- coding: utf-8 -*-
"""ner/ner_extractor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pNFFNATwEPf2KIEu-awSYeI5xe8hp0cU
"""

# ner/ner_extractor.py

"""
BERT-based Named Entity Recognizer
------------------------------------
Uses HuggingFace's pretrained NER pipeline built on BERT.

Model: dbmdz/bert-large-cased-finetuned-conll03-english
  - Trained on CoNLL-2003 NER benchmark dataset
  - Recognizes 4 entity types:
      PER  → Person names       (e.g., "Isaac Newton")
      ORG  → Organizations      (e.g., "MIT", "Google")
      LOC  → Locations          (e.g., "Paris", "India")
      MISC → Miscellaneous      (e.g., "English", "Olympics")

How BERT NER works:
  1. Tokenize sentence into subword tokens
  2. BERT reads ALL tokens simultaneously (bidirectional)
  3. For each token → predict entity label (B-PER, I-PER, O, etc.)
  4. Merge subword tokens back into full words

B- prefix = Beginning of entity  ("B-PER" = first token of a person name)
I- prefix = Inside entity         ("I-PER" = continuation of person name)
O  label  = Outside (not entity)
"""

import re


# ── Entity type mapping ─────────────────────────────────────────
# Map BERT's labels to human-friendly names + emojis
ENTITY_TYPE_MAP = {
    "PERSON"                   : ("PERSON",                   "👤"),
    "ORGANIZATION"             : ("ORGANIZATION",             "🏢"),
    "LOCATION"                 : ("LOCATION",                 "📍"),
    "DATES_DEADLINES"          : ("DATES & DEADLINES",        "📅"),
    "FINANCIAL_VALUES"         : ("FINANCIAL & CONTRACT VALUE","💰"),
    "PAYMENT_RENEWAL"          : ("PAYMENT & RENEWAL TERMS",  "💳"),
    "OBLIGATIONS"              : ("OBLIGATIONS & RESPONSIBILITY","📜"),
    "PENALTY_RISKS"            : ("PENALTY & RISK CLAUSES",   "⚠️"),
    "MISCELLANEOUS"            : ("MISCELLANEOUS",            "🔖"),
}


# Global pipeline instance (load once, reuse)
_ner_pipeline = None


import logging
log = logging.getLogger("lexi.ner.ner_extractor")


def get_ner_pipeline():
    """Loads the BERT NER pipeline once (lazy) and reuses it."""
    global _ner_pipeline
    if _ner_pipeline is None:
        from transformers import pipeline   # lazy: heavy import, only needed for entity extraction
        log.info("[NER] Loading BERT NER model (first time ~30 seconds)...")
        _ner_pipeline = pipeline(
            task="ner",
            model="dbmdz/bert-large-cased-finetuned-conll03-english",
            aggregation_strategy="simple",   # merge subword tokens back into whole words
        )
        log.info("[NER] BERT NER model loaded! ✅")
    return _ner_pipeline


def _split_into_chunks(text: str, max_chars: int = 400) -> list:
    """Split text on sentence boundaries into chunks small enough for BERT's 512-token limit."""
    sentences = re.split(r"(?<=[.!?])\s+", text)
    chunks, current = [], ""
    for sentence in sentences:
        if len(current) + len(sentence) < max_chars:
            current += " " + sentence
        else:
            if current.strip():
                chunks.append(current.strip())
            current = sentence
    if current.strip():
        chunks.append(current.strip())
    return chunks


def _organize_entities(raw_entities: list, text: str = "") -> dict:
    """
    Converts raw BERT output + rule extraction into enterprise business categories.
    """
    organized = {
        "PERSON"                  : [],
        "ORGANIZATION"            : [],
        "LOCATION"                : [],
        "DATES_DEADLINES"         : [],
        "FINANCIAL_VALUES"        : [],
        "PAYMENT_RENEWAL"         : [],
        "OBLIGATIONS"             : [],
        "PENALTY_RISKS"           : [],
        "MISCELLANEOUS"           : [],
    }

    seen = set()

    for entity in raw_entities:
        entity_group = entity.get("entity_group", "")
        word         = entity.get("word", "").strip()
        score        = entity.get("score", 0.0)

        if score < 0.75:
            continue

        word = re.sub(r"##", "", word).strip()
        if len(word) < 2 or word.lower() in seen:
            continue

        if entity_group == "PER":
            organized["PERSON"].append(word)
        elif entity_group == "ORG":
            organized["ORGANIZATION"].append(word)
        elif entity_group == "LOC":
            organized["LOCATION"].append(word)
        elif entity_group == "MISC":
            organized["MISCELLANEOUS"].append(word)

        seen.add(word.lower())

    # Business Regex & Rule-Based Extractors
    if text:
        # Dates & Deadlines
        dates = re.findall(r"\b(?:\d{1,2}[-/th|st|nd|rd]*\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*|\d{4}[-/]\d{2}[-/]\d{2}|within \d+ days|deadline|effective date)\b", text, re.IGNORECASE)
        for d in dates:
            if d.lower() not in seen and len(d) > 3:
                organized["DATES_DEADLINES"].append(d.strip())
                seen.add(d.lower())

        # Financial Values & Contract Values
        fin = re.findall(r"(?:[\$€£₹]\s?\d+(?:,\d+)*(?:\.\d+)?|\b\d+\s?(?:USD|INR|EUR|GBP|million|billion|k)\b)", text, re.IGNORECASE)
        for f in fin:
            if f.lower() not in seen:
                organized["FINANCIAL_VALUES"].append(f.strip())
                seen.add(f.lower())

        # Payment & Renewal Terms
        terms = re.findall(r"\b(?:Net \d+|auto-renew[a-z]*|annual renewal|monthly billing|grace period|upfront payment)\b", text, re.IGNORECASE)
        for t in terms:
            if t.lower() not in seen:
                organized["PAYMENT_RENEWAL"].append(t.strip())
                seen.add(t.lower())

        # Obligations & Sentence Analysis
        sents = re.split(r'(?<=[.!?])\s+', text)
        for s in sents:
            sl = s.lower()
            if any(k in sl for k in ["shall", "must", "agrees to", "responsible for", "obligat"]):
                if len(s.strip()) > 15 and s.strip() not in organized["OBLIGATIONS"]:
                    organized["OBLIGATIONS"].append(s.strip()[:140])
            if any(k in sl for k in ["penalty", "liability", "indemni", "breach", "termination", "liquidated damages"]):
                if len(s.strip()) > 15 and s.strip() not in organized["PENALTY_RISKS"]:
                    organized["PENALTY_RISKS"].append(s.strip()[:140])

    return organized


def extract_entities(text: str) -> dict:
    """Extracts named business entities and contract clauses from text."""
    if not text or not text.strip():
        return {k: [] for k in ENTITY_TYPE_MAP.keys()}

    ner = get_ner_pipeline()
    chunks = _split_into_chunks(text, max_chars=400)

    all_raw_entities = []
    for chunk in chunks:
        if chunk.strip():
            try:
                raw = ner(chunk)
                all_raw_entities.extend(raw)
            except Exception as e:
                log.warning(f"[NER] Chunk error: {e}")

    organized = _organize_entities(all_raw_entities, text=text)
    return organized


def format_entities_for_display(entities: dict) -> str:
    """Formats extracted business entities and clauses into readable markdown."""
    lines = ["📌 **Extracted Business Entities & Contract Clauses**\n"]
    total = sum(len(v) for v in entities.values())

    if total == 0:
        return "No business entities or contract clauses detected in this document."

    for key, (label, emoji) in ENTITY_TYPE_MAP.items():
        words = entities.get(key, [])
        if not words:
            continue

        lines.append(f"{emoji} **{label}** ({len(words)} extracted):")
        for word in words[:8]:
            lines.append(f"   • {word}")
        if len(words) > 8:
            lines.append(f"   • *...and {len(words)-8} more*")
        lines.append("")

    lines.append(f"Total Provisions & Entities Extracted: {total}")
    return "\n".join(lines)


def extract_entities_from_sentences(sentences: list) -> list:
    """Runs entity & clause extraction across document sentences."""
    results = []
    for sentence in sentences:
        if not sentence.strip():
            continue
        entities = _organize_entities([], text=sentence)
        total = sum(len(v) for v in entities.values())
        if total > 0:
            results.append((sentence, entities))
    return results