"""initial schema

Revision ID: 3820b6d6ad4d
Revises: 
Create Date: 2026-09-26 08:21:19.781283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3820b6d6ad4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.String(length=40), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('kb_sessions',
    sa.Column('sid', sa.String(length=32), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=1024), nullable=True),
    sa.Column('pages', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('faiss_index', sa.LargeBinary(), nullable=True),
    sa.Column('chunks', sa.JSON(), nullable=True),
    sa.Column('pipeline_result', sa.JSON(), nullable=True),
    sa.Column('summary_result', sa.Text(), nullable=True),
    sa.Column('compliance_result', sa.JSON(), nullable=True),
    sa.Column('entities_result', sa.JSON(), nullable=True),
    sa.Column('action_items_result', sa.JSON(), nullable=True),
    sa.Column('briefing_history', sa.JSON(), nullable=True),
    sa.Column('compliance_history', sa.JSON(), nullable=True),
    sa.Column('entities_history', sa.JSON(), nullable=True),
    sa.Column('action_items_history', sa.JSON(), nullable=True),
    sa.Column('zero_retention', sa.Boolean(), nullable=True),
    sa.Column('last_audited_question', sa.Text(), nullable=True),
    sa.Column('qa_confidences', sa.JSON(), nullable=True),
    sa.Column('flat_ingestion', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('kb_sessions')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
