"""add qa and search history

Revision ID: d62bfb6907ee
Revises: 3820b6d6ad4d
Create Date: 2026-09-26 09:09:09.883225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd62bfb6907ee'
down_revision: Union[str, Sequence[str], None] = '3820b6d6ad4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_sessions', sa.Column('qa_history', sa.JSON(), nullable=True))
    op.add_column('kb_sessions', sa.Column('search_history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kb_sessions', 'search_history')
    op.drop_column('kb_sessions', 'qa_history')
    # ### end Alembic commands ###
