# models/training_data.py
"""
Training dataset for the contract-sentence tagger used by /clustering — labels match the tags
that page has always offered (webapp/blueprints/features.py), replacing the keyword-substring
heuristic that used to power it. ~40 hand-written sentences per tag, styled like real contract
provisions (MSAs, SOWs, DPAs) rather than academic text.
"""

LABEL_MAP = {"Risk": 0, "Decision": 1, "Action Item": 2, "Deadline": 3,
             "Financial": 4, "Compliance": 5, "Obligation": 6}
ID_TO_LABEL = {v: k for k, v in LABEL_MAP.items()}

TRAINING_DATA = [
    # ── Risk ─────────────────────────────────────────────────────────────
    ("Neither party shall be liable for indirect, incidental, or consequential damages arising from this agreement.", "Risk"),
    ("In no event shall either party's aggregate liability exceed the total fees paid in the preceding twelve months.", "Risk"),
    ("The Client acknowledges that delays caused by third-party integrations are outside the Vendor's control and risk.", "Risk"),
    ("A material breach of the confidentiality provisions exposes the breaching party to injunctive relief and damages.", "Risk"),
    ("The Vendor disclaims all warranties, express or implied, including merchantability and fitness for a particular purpose.", "Risk"),
    ("Any unauthorized use of the licensed software is at the sole risk of the party committing the unauthorized use.", "Risk"),
    ("Force majeure events, including natural disasters and government action, relieve the affected party from liability for delay.", "Risk"),
    ("The Company shall not be responsible for any loss of data resulting from the Customer's failure to maintain backups.", "Risk"),
    ("Exposure to currency fluctuation risk shall be borne exclusively by the party receiving payment in foreign currency.", "Risk"),
    ("The indemnifying party bears the risk of third-party claims arising from its own negligence or willful misconduct.", "Risk"),
    ("A security breach affecting personal data could expose the Processor to regulatory fines and reputational harm.", "Risk"),
    ("The parties recognize that reliance on a single supplier introduces concentration risk to the supply chain.", "Risk"),
    ("Termination of this agreement without cause may result in stranded costs that the terminating party must absorb.", "Risk"),
    ("The Contractor assumes all risk of loss or damage to equipment while it is in transit to the job site.", "Risk"),
    ("Non-compliance with export control laws could subject either party to civil and criminal penalties.", "Risk"),
    ("The insurer's coverage does not extend to losses caused by the Insured's own fraudulent conduct.", "Risk"),
    ("A downgrade in the Guarantor's credit rating constitutes a risk factor requiring immediate disclosure.", "Risk"),
    ("Uninsured cyber incidents remain a residual risk retained by the Customer under this agreement.", "Risk"),
    ("The warranty excludes defects caused by misuse, unauthorized modification, or ordinary wear and tear.", "Risk"),
    ("Litigation arising from patent infringement claims poses a material risk to the licensed product line.", "Risk"),
    ("The parties acknowledge that market volatility may adversely affect the value of the escrowed shares.", "Risk"),
    ("Failure to renew the required permits exposes the Operator to suspension of its operating license.", "Risk"),
    ("The Supplier bears the risk of obsolescence for any inventory held beyond the agreed forecast period.", "Risk"),
    ("Reliance on unaudited financial statements carries a risk of misstatement that the Buyer accepts knowingly.", "Risk"),
    ("A single point of failure in the hosting infrastructure represents an unacceptable risk to service continuity.", "Risk"),
    ("The Licensee assumes the risk that the licensed technology may not achieve the anticipated performance benchmarks.", "Risk"),
    ("Cross-border data transfers carry heightened risk of exposure to inconsistent privacy regimes.", "Risk"),
    ("The Borrower's default on any covenant increases the risk of acceleration of the entire outstanding balance.", "Risk"),
    ("Environmental contamination discovered after closing remains a risk allocated to the Seller under this clause.", "Risk"),
    ("The absence of a succession plan for key personnel is identified as an operational risk in the audit.", "Risk"),
    ("Reputational risk from a public data breach could materially impair the Company's customer relationships.", "Risk"),
    ("The parties agree that interest rate volatility poses a risk to the projected cost of the financing.", "Risk"),
    ("Any use of the platform in violation of the acceptable use policy is undertaken entirely at the user's risk.", "Risk"),
    ("Concentration of revenue in a small number of customers is flagged as a going-concern risk.", "Risk"),
    ("The Vendor's subcontracting of critical functions introduces additional counterparty risk for the Client.", "Risk"),
    ("Unpatched vulnerabilities in third-party libraries present an ongoing security risk to the platform.", "Risk"),
    ("The Guarantor's obligations do not cover losses attributable to the Lender's own gross negligence.", "Risk"),
    ("A sudden change in applicable tariffs could materially increase the landed cost risk for imported goods.", "Risk"),
    ("The parties acknowledge inherent risk in relying on a single cloud provider for disaster recovery.", "Risk"),
    ("Early termination fees are designed to compensate the Vendor for the risk of stranded capacity investment.", "Risk"),

    # ── Decision ─────────────────────────────────────────────────────────
    ("The Board of Directors has approved the proposed merger subject to shareholder ratification.", "Decision"),
    ("The Steering Committee determined that the project would proceed to Phase 2 without further review.", "Decision"),
    ("Following due diligence, the Buyer elected to proceed with the acquisition on the terms disclosed herein.", "Decision"),
    ("The arbitrator ruled in favor of the Claimant on all counts presented in the dispute.", "Decision"),
    ("Management decided to consolidate the two regional offices into a single headquarters location.", "Decision"),
    ("The Compliance Officer determined that the proposed marketing campaign did not violate applicable regulations.", "Decision"),
    ("After reviewing the bids, the Procurement Committee selected the second-lowest bidder based on technical merit.", "Decision"),
    ("The Court held that the non-compete clause was unenforceable as an unreasonable restraint of trade.", "Decision"),
    ("The parties agreed to resolve the dispute through binding arbitration rather than litigation.", "Decision"),
    ("The Investment Committee approved the allocation of additional capital to the expansion project.", "Decision"),
    ("Following the audit, the Company chose to restate its prior-year financial statements.", "Decision"),
    ("The Executive Committee resolved to suspend all discretionary bonuses for the current fiscal year.", "Decision"),
    ("The Licensor decided not to renew the exclusive distribution rights beyond the initial term.", "Decision"),
    ("The regulator concluded that the merger would not substantially lessen competition in the relevant market.", "Decision"),
    ("The Board voted unanimously to appoint a new Chief Financial Officer effective the following quarter.", "Decision"),
    ("The mediator recommended a settlement figure that both parties subsequently accepted.", "Decision"),
    ("Senior management determined that the vendor's non-performance justified immediate termination for cause.", "Decision"),
    ("The Credit Committee declined to extend additional financing beyond the existing facility limit.", "Decision"),
    ("The parties jointly resolved to extend the negotiation period by an additional thirty days.", "Decision"),
    ("The Data Protection Officer determined that a breach notification to the regulator was required.", "Decision"),
    ("The Underwriting Committee decided to exclude flood damage from the renewed policy.", "Decision"),
    ("Following deliberation, the jury found in favor of the defendant on the breach of contract claim.", "Decision"),
    ("The Product Committee chose to deprioritize the feature request in favor of the security roadmap.", "Decision"),
    ("The Trustees resolved to distribute the remaining trust assets in accordance with the beneficiaries' shares.", "Decision"),
    ("The parties determined that English law would govern the interpretation of this agreement.", "Decision"),
    ("The Audit Committee decided that no further investigation into the whistleblower report was warranted.", "Decision"),
    ("The Landlord elected to exercise its option to terminate the lease upon the tenant's default.", "Decision"),
    ("The panel determined that the technical specification met the requirements of the tender.", "Decision"),
    ("The Shareholders voted to approve the amended articles of association at the annual general meeting.", "Decision"),
    ("The Risk Committee decided to reduce the Company's exposure to the affected counterparty.", "Decision"),
    ("Management resolved to outsource the customer support function to a third-party provider.", "Decision"),
    ("The Tender Board determined that the lowest bid did not meet the minimum technical threshold.", "Decision"),
    ("The parties agreed by mutual consent to waive the notice period for this particular renewal.", "Decision"),
    ("The Ethics Committee ruled that the proposed research protocol satisfied all disclosure requirements.", "Decision"),
    ("The Insurer decided to settle the claim rather than proceed to a coverage dispute.", "Decision"),
    ("The Franchisor determined not to approve the proposed transfer of the franchise to a third party.", "Decision"),
    ("The Committee concluded that the vendor's certifications were sufficient to satisfy the audit requirement.", "Decision"),
    ("The parties resolved their pricing dispute through an independent expert determination.", "Decision"),
    ("The Board decided to defer the dividend payment pending clarification of the tax treatment.", "Decision"),
    ("The Selection Panel chose the incumbent supplier for renewal based on historical performance.", "Decision"),

    # ── Action Item ──────────────────────────────────────────────────────
    ("The Vendor shall deliver the signed statement of work to the Client no later than Friday.", "Action Item"),
    ("Priya will prepare the revised budget forecast and circulate it to the finance team.", "Action Item"),
    ("The Contractor must submit updated insurance certificates before commencing work on site.", "Action Item"),
    ("The project manager is to schedule a kickoff call with all stakeholders this week.", "Action Item"),
    ("Legal shall review the amended indemnification clause and provide comments by Wednesday.", "Action Item"),
    ("The Data Protection Officer will conduct a privacy impact assessment prior to system launch.", "Action Item"),
    ("The Supplier is required to send replacement parts for the defective units identified in the audit.", "Action Item"),
    ("Sam needs to follow up with the vendor regarding the outstanding invoice discrepancy.", "Action Item"),
    ("The IT team shall migrate the affected servers to the new data center over the weekend.", "Action Item"),
    ("The Client must provide access credentials to the Contractor before testing can begin.", "Action Item"),
    ("The HR department will update the employee handbook to reflect the new remote work policy.", "Action Item"),
    ("The Auditor is to issue the final report within ten business days of completing fieldwork.", "Action Item"),
    ("Marketing shall finalize the campaign creative and submit it for legal review by month-end.", "Action Item"),
    ("The Engineering team needs to patch the identified vulnerability before the next release.", "Action Item"),
    ("The Landlord will arrange for the elevator inspection required under the building code.", "Action Item"),
    ("The Procurement team shall issue a purchase order once the statement of work is countersigned.", "Action Item"),
    ("The Compliance team must file the annual regulatory disclosure with the relevant authority.", "Action Item"),
    ("The Consultant is to deliver the training materials to the Client's staff by the agreed date.", "Action Item"),
    ("Operations will reconcile the inventory count against the warehouse management system records.", "Action Item"),
    ("The Vendor shall assign a dedicated account manager to the Client's account within five days.", "Action Item"),
    ("The Finance team needs to process the outstanding reimbursement claims before quarter close.", "Action Item"),
    ("The Security team shall rotate all administrative credentials following the incident.", "Action Item"),
    ("The Contractor is required to obtain the necessary building permits prior to breaking ground.", "Action Item"),
    ("Customer Success will schedule a quarterly business review with the account within thirty days.", "Action Item"),
    ("The Translator must deliver the localized documentation in all required languages by the deadline.", "Action Item"),
    ("The Payroll team shall correct the withholding error identified in last month's audit.", "Action Item"),
    ("The Vendor is to conduct a root cause analysis and share findings with the Client's team.", "Action Item"),
    ("The Project Sponsor will approve the change request before development work can resume.", "Action Item"),
    ("The Warehouse team must complete the cycle count before the new shipment arrives.", "Action Item"),
    ("Legal shall circulate the final execution copy of the agreement for signature.", "Action Item"),
    ("The Support team needs to update the knowledge base article to reflect the product change.", "Action Item"),
    ("The Contractor shall remove all debris from the site upon completion of the works.", "Action Item"),
    ("The Client must nominate an authorized signatory for the amended purchase agreement.", "Action Item"),
    ("The QA team will execute the regression suite before the release is promoted to production.", "Action Item"),
    ("The Vendor is to provide a remediation plan addressing each finding in the audit report.", "Action Item"),
    ("The Facilities team shall replace the fire suppression system components flagged in the inspection.", "Action Item"),
    ("The Account Manager needs to escalate the unresolved ticket to the engineering team.", "Action Item"),
    ("The Client shall return all leased equipment within the timeframe specified in this section.", "Action Item"),
    ("The Recruiter will schedule interviews for the shortlisted candidates by the end of the week.", "Action Item"),
    ("The Vendor must reissue the corrected invoice reflecting the agreed discount.", "Action Item"),

    # ── Deadline ─────────────────────────────────────────────────────────
    ("The Client must provide written notice of termination at least ninety days prior to the renewal date.", "Deadline"),
    ("All deliverables under this statement of work shall be completed no later than December 15.", "Deadline"),
    ("Payment is due within thirty days of the invoice date, subject to a late fee thereafter.", "Deadline"),
    ("The warranty period expires twelve months from the date of delivery.", "Deadline"),
    ("Either party may terminate this agreement upon sixty days' written notice to the other party.", "Deadline"),
    ("The Tenant shall vacate the premises no later than the last day of the lease term.", "Deadline"),
    ("Claims for defective goods must be submitted within fourteen days of receipt.", "Deadline"),
    ("The Contractor shall achieve substantial completion within one hundred eighty days of the notice to proceed.", "Deadline"),
    ("The option to renew must be exercised in writing no less than ninety days before expiration.", "Deadline"),
    ("The final report is due to the regulator by the last business day of the fiscal quarter.", "Deadline"),
    ("The escrow period shall run for eighteen months following the closing date.", "Deadline"),
    ("The Buyer must complete due diligence within forty-five days of the effective date.", "Deadline"),
    ("Notice of a dispute must be given within thirty days of the event giving rise to the claim.", "Deadline"),
    ("The grace period for curing a payment default shall not exceed ten business days.", "Deadline"),
    ("The registration must be renewed annually on or before the anniversary of the original filing.", "Deadline"),
    ("The Supplier shall replace nonconforming goods within five business days of notification.", "Deadline"),
    ("This agreement shall automatically renew unless either party provides notice sixty days in advance.", "Deadline"),
    ("The initial term of this agreement expires three years from the effective date.", "Deadline"),
    ("The Contractor's punch list items must be resolved within thirty days of substantial completion.", "Deadline"),
    ("The Employee's probationary period concludes ninety days after the start date.", "Deadline"),
    ("The insurance certificate must be renewed no later than five days before the current policy expires.", "Deadline"),
    ("The parties shall complete the technology transfer within six months of signing.", "Deadline"),
    ("A response to the arbitration demand must be filed within twenty-one days of service.", "Deadline"),
    ("The loan matures five years from the date of the first drawdown.", "Deadline"),
    ("The confidentiality obligations survive for five years following termination of this agreement.", "Deadline"),
    ("The Licensee must cease all use of the marks within thirty days of termination.", "Deadline"),
    ("The audit must be completed prior to the close of the current reporting period.", "Deadline"),
    ("The Vendor shall provide the annual compliance certificate by January 31 of each year.", "Deadline"),
    ("The parties must complete the data migration before the legacy system is decommissioned on June 1.", "Deadline"),
    ("The right of first refusal must be exercised within fifteen days of receiving the offer notice.", "Deadline"),
    ("The construction schedule requires foundation work to be finished within sixty days of mobilization.", "Deadline"),
    ("The Distributor's exclusivity period expires two years after the launch date.", "Deadline"),
    ("Interest on overdue amounts accrues from the date payment was originally due.", "Deadline"),
    ("The parties shall hold a renewal negotiation meeting no later than ninety days before expiry.", "Deadline"),
    ("The Guarantor's obligations terminate automatically five years after the guarantee is issued.", "Deadline"),
    ("The Seller must deliver clear title to the property at or before the closing date.", "Deadline"),
    ("The pilot program shall run for a period of ninety days from the launch date.", "Deadline"),
    ("The appeal must be lodged within thirty calendar days of the decision being issued.", "Deadline"),
    ("The Supplier's price protection guarantee expires six months after the order date.", "Deadline"),
    ("The parties agree to complete the handover within ten business days of contract signature.", "Deadline"),

    # ── Financial ────────────────────────────────────────────────────────
    ("The Client shall pay a monthly subscription fee of USD 12,500, invoiced in advance.", "Financial"),
    ("A late payment penalty of one and a half percent per month applies to overdue balances.", "Financial"),
    ("The total contract value, inclusive of all fees and expenses, shall not exceed USD 2.4 million.", "Financial"),
    ("The Vendor shall issue a credit note for any amounts overbilled in the prior period.", "Financial"),
    ("The Buyer shall pay a deposit equal to twenty percent of the purchase price upon signing.", "Financial"),
    ("Currency conversion for cross-border payments shall use the exchange rate published on the payment date.", "Financial"),
    ("The Company's annual revenue for the period was reported at USD 48.7 million.", "Financial"),
    ("The royalty rate applicable to net sales is fixed at five percent for the term of this agreement.", "Financial"),
    ("The Lender shall disburse the loan proceeds in three equal installments of USD 500,000 each.", "Financial"),
    ("All fees under this agreement are exclusive of applicable sales, use, and value-added taxes.", "Financial"),
    ("The escrow account shall hold USD 750,000 pending resolution of any indemnification claims.", "Financial"),
    ("The Distributor shall pay a minimum annual purchase commitment of USD 1 million.", "Financial"),
    ("Reimbursable expenses shall not exceed ten percent of the total professional services fees.", "Financial"),
    ("The purchase price shall be adjusted based on the net working capital at closing.", "Financial"),
    ("The Company issued 500,000 shares of preferred stock at a price of USD 10 per share.", "Financial"),
    ("The interest rate on the outstanding balance is fixed at six percent per annum.", "Financial"),
    ("The Franchisee shall pay an ongoing royalty of eight percent of gross monthly sales.", "Financial"),
    ("A one-time implementation fee of USD 35,000 is due upon execution of this agreement.", "Financial"),
    ("The Insurer shall pay the policy limit of USD 5 million in the event of a covered total loss.", "Financial"),
    ("Net proceeds from the asset sale shall be distributed pro rata among the shareholders.", "Financial"),
    ("The management fee is calculated as two percent of assets under management, payable quarterly.", "Financial"),
    ("The Supplier offers a volume discount of ten percent on orders exceeding 10,000 units.", "Financial"),
    ("The security deposit of USD 25,000 shall be refunded within thirty days of lease termination.", "Financial"),
    ("The earn-out payment is capped at USD 3 million based on achievement of revenue targets.", "Financial"),
    ("The Company's operating margin improved to eighteen percent in the most recent fiscal year.", "Financial"),
    ("A break fee of USD 1.5 million is payable if the Seller accepts a competing offer.", "Financial"),
    ("The Client shall reimburse pre-approved travel expenses at actual cost, without markup.", "Financial"),
    ("The bond is issued with a face value of USD 10 million and a coupon rate of four percent.", "Financial"),
    ("The parties agree to a price escalation of three percent annually tied to the consumer price index.", "Financial"),
    ("The settlement amount of USD 400,000 shall be paid in full within thirty days of execution.", "Financial"),
    ("The Underwriter's commission is set at seven percent of the gross proceeds of the offering.", "Financial"),
    ("The Tenant's base rent shall increase by two percent each year of the lease term.", "Financial"),
    ("The Vendor shall extend a rebate of five percent for payments made within ten days.", "Financial"),
    ("The total consideration for the acquisition consists of cash and stock valued at USD 20 million.", "Financial"),
    ("Overpayments identified during reconciliation shall be refunded within fifteen business days.", "Financial"),
    ("The line of credit provides for borrowings of up to USD 8 million at a variable interest rate.", "Financial"),
    ("The licensing fee is structured as a one-time payment of USD 250,000 plus ongoing royalties.", "Financial"),
    ("The Company recorded a net loss of USD 2.1 million for the quarter, driven by one-time charges.", "Financial"),
    ("The parties shall split the transaction costs equally, up to a cap of USD 50,000.", "Financial"),
    ("The dividend payable to preferred shareholders accrues at eight percent per annum, compounding annually.", "Financial"),

    # ── Compliance ───────────────────────────────────────────────────────
    ("The Processor shall comply with the General Data Protection Regulation in handling personal data.", "Compliance"),
    ("Each party shall maintain compliance with all applicable anti-bribery and anti-corruption laws.", "Compliance"),
    ("The Supplier warrants that its products conform to the applicable ISO 9001 quality standards.", "Compliance"),
    ("The Company shall adhere to the Payment Card Industry Data Security Standard for all card transactions.", "Compliance"),
    ("The Contractor shall comply with all applicable occupational health and safety regulations.", "Compliance"),
    ("The parties shall conduct all export activities in accordance with applicable export control laws.", "Compliance"),
    ("The Bank shall maintain policies consistent with anti-money laundering regulatory requirements.", "Compliance"),
    ("The Vendor's data handling practices shall conform to the requirements of the CCPA.", "Compliance"),
    ("The manufacturer certifies that the goods comply with all applicable safety and labeling regulations.", "Compliance"),
    ("The Company shall maintain its SOC 2 Type II certification for the duration of this agreement.", "Compliance"),
    ("Each party shall comply with applicable sanctions laws in connection with this agreement.", "Compliance"),
    ("The Employer shall comply with all applicable wage and hour laws in each jurisdiction of operation.", "Compliance"),
    ("The Licensee shall use the software only in compliance with the accompanying end-user license terms.", "Compliance"),
    ("The clinical trial shall be conducted in accordance with Good Clinical Practice guidelines.", "Compliance"),
    ("The Advertiser shall ensure all marketing claims comply with applicable consumer protection laws.", "Compliance"),
    ("The Company shall maintain compliance with the Sarbanes-Oxley Act's internal control requirements.", "Compliance"),
    ("The Contractor shall comply with all applicable building codes and zoning ordinances.", "Compliance"),
    ("The parties shall handle all patient information in accordance with HIPAA requirements.", "Compliance"),
    ("The fund shall comply with the investment restrictions set out in its governing prospectus.", "Compliance"),
    ("The Broker shall maintain licensure in each state where it conducts regulated activities.", "Compliance"),
    ("The Supplier shall comply with the Conflict Minerals provisions of the Dodd-Frank Act.", "Compliance"),
    ("The facility shall operate in compliance with all applicable environmental permits and regulations.", "Compliance"),
    ("The Company shall comply with the Foreign Corrupt Practices Act in all international dealings.", "Compliance"),
    ("The Processor shall implement technical measures required under applicable data protection law.", "Compliance"),
    ("The Airline shall comply with all applicable aviation safety regulations issued by the authority.", "Compliance"),
    ("The Reseller shall comply with the manufacturer's authorized channel policies at all times.", "Compliance"),
    ("The Company's financial statements shall be prepared in accordance with generally accepted accounting principles.", "Compliance"),
    ("The Contractor shall comply with all prevailing wage requirements applicable to public works projects.", "Compliance"),
    ("The parties shall maintain records sufficient to demonstrate compliance with the audit requirements.", "Compliance"),
    ("The Food Manufacturer shall comply with all applicable FDA labeling and safety regulations.", "Compliance"),
    ("The Insurer shall comply with the solvency requirements imposed by the state insurance regulator.", "Compliance"),
    ("The Company shall maintain compliance with the accessibility requirements of the ADA for its website.", "Compliance"),
    ("The Vendor shall comply with the Client's information security policy as updated from time to time.", "Compliance"),
    ("The Miner shall comply with all applicable mine safety regulations issued by the relevant authority.", "Compliance"),
    ("The parties shall comply with applicable whistleblower protection laws in handling complaints.", "Compliance"),
    ("The Telecom Operator shall comply with the regulator's data retention requirements.", "Compliance"),
    ("The Fund Manager shall comply with the disclosure obligations under applicable securities law.", "Compliance"),
    ("The Distributor shall ensure downstream compliance with the product's regulatory approvals.", "Compliance"),
    ("The Employer shall comply with immigration law requirements when sponsoring foreign workers.", "Compliance"),
    ("The Company shall maintain compliance with the listing rules of the relevant stock exchange.", "Compliance"),

    # ── Obligation ───────────────────────────────────────────────────────
    ("The Supplier shall maintain the confidentiality of all proprietary information disclosed under this agreement.", "Obligation"),
    ("Each party shall indemnify and hold harmless the other from claims arising out of its own negligence.", "Obligation"),
    ("The Licensee shall not sublicense, assign, or transfer its rights without the Licensor's prior written consent.", "Obligation"),
    ("The Tenant shall keep the premises in good repair throughout the term of the lease.", "Obligation"),
    ("The Vendor shall provide technical support during standard business hours for the term of this agreement.", "Obligation"),
    ("The Borrower shall maintain the collateral in good condition and insured against loss.", "Obligation"),
    ("Each party shall use commercially reasonable efforts to perform its obligations under this agreement.", "Obligation"),
    ("The Employee shall devote substantially all of their working time to the business of the Company.", "Obligation"),
    ("The Manufacturer shall maintain product liability insurance throughout the term of this agreement.", "Obligation"),
    ("The Contractor shall perform all work in a good and workmanlike manner consistent with industry standards.", "Obligation"),
    ("The Distributor shall use its best efforts to promote and sell the products within the territory.", "Obligation"),
    ("The Company shall maintain accurate books and records in accordance with its ordinary course of business.", "Obligation"),
    ("The Franchisee shall operate the franchise in accordance with the Franchisor's operations manual.", "Obligation"),
    ("The Landlord shall maintain the structural elements of the building throughout the lease term.", "Obligation"),
    ("Each party shall notify the other promptly upon becoming aware of a security incident.", "Obligation"),
    ("The Consultant shall not engage in any activity that conflicts with its duties under this agreement.", "Obligation"),
    ("The Seller shall deliver the goods free and clear of all liens and encumbrances.", "Obligation"),
    ("The Licensee shall display the required trademark notices on all licensed products.", "Obligation"),
    ("The Guarantor shall remain liable for the Borrower's obligations until the loan is repaid in full.", "Obligation"),
    ("The Servicer shall service the loans in accordance with customary and usual servicing practices.", "Obligation"),
    ("Each party shall bear its own costs and expenses incurred in connection with this agreement.", "Obligation"),
    ("The Employer shall provide a safe working environment in accordance with its policies.", "Obligation"),
    ("The Vendor shall maintain sufficient inventory to meet the Client's reasonably anticipated demand.", "Obligation"),
    ("The Trustee shall act in the best interests of the beneficiaries at all times.", "Obligation"),
    ("The Contractor shall obtain and maintain all licenses necessary to perform the services.", "Obligation"),
    ("The Company shall not disclose the terms of this agreement without the other party's consent.", "Obligation"),
    ("The Operator shall maintain the equipment in accordance with the manufacturer's specifications.", "Obligation"),
    ("The Distributor shall not represent competing products without the Manufacturer's prior consent.", "Obligation"),
    ("Each party shall designate a representative authorized to act on its behalf under this agreement.", "Obligation"),
    ("The Buyer shall accept delivery of the goods in accordance with the agreed shipping terms.", "Obligation"),
    ("The Escrow Agent shall hold the funds in accordance with the terms of the escrow agreement.", "Obligation"),
    ("The Licensor shall provide reasonable technical assistance to support the Licensee's implementation.", "Obligation"),
    ("The Joint Venture partners shall contribute capital in proportion to their respective ownership interests.", "Obligation"),
    ("The Employee shall return all Company property upon termination of employment.", "Obligation"),
    ("The Reinsurer shall promptly pay its share of losses ceded under this treaty.", "Obligation"),
    ("The Company shall provide the Auditor with full access to its books and records.", "Obligation"),
    ("The Charterer shall redeliver the vessel in the same condition as when delivered, ordinary wear excepted.", "Obligation"),
    ("The Manager shall act in accordance with the investment guidelines set by the Client.", "Obligation"),
    ("The Vendor shall maintain business continuity plans sufficient to meet the agreed service levels.", "Obligation"),
    ("Each party shall cooperate in good faith to resolve any disputes arising under this agreement.", "Obligation"),
]
